### ISSUE TITLE
[Android] Fail build with license key

### ISSUE THREAD

**Issue by AdamJB** [notifee/react-native-notifee#103]
Hi. I recently got the license for Notifee, and now when building in android, it's failing with the following error:
```
FAILURE: Build failed with an exception.

* Where:
Script '/Users/.../node_modules/@notifee/react-native/android/notifee-json.gradle' line: 253

* What went wrong:
A problem occurred configuring project ':@notifee_react-native'.
> Could not get unknown property 'android' for project ':app' of type org.gradle.api.Project.

```

**Comment by mikehardy** [comment]
I wonder if you are seeing the problem fixed by this? https://github.com/notifee/react-native-notifee/pull/100

The patch there is super super small, you should be able to reach right in to node_modules/@notifee/react-native/android/build.gradle to apply the change locally and see if it fixes it

If it does, then you can use https://github.com/ds300/patch-package to persist the change until it's merged+released (after install it's just `cd android && ./gradlew clean && cd .. && npx patch-package @notifee/react-native` followed by whatever source control stuff you need and you're set - if you've never used patch-package)

**Comment by AdamJB** [comment]
I wound up fixing the issue by yarn removing react native completely, and re installing it.  It looks like there were some dependency updates to RN 0.60.2 that got pulled via yarn.lock and resolved it.

Thanks,
- Adam
