### ISSUE TITLE
Building for Android cannot add task >= 0.10

### ISSUE THREAD

**Issue by lkwjohn** [notifee/react-native-notifee#122]
Using version 0.10 and above of notifee, I'm encountering error during building.
When I fall back to 0.9.1, it was able to build again although I need to do a patch of the notifee-json.gradle to fix the error of ([Android]: Fixed an issue with notifee.config.json where sometimes the script could not find the 'app' gradle project automatically.)

React-Native: 0.60.6
Notifee: >= 0.10.0

Error: Command failed: ./gradlew app:installDevDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* Where:
Script '/xxxx/node_modules/@notifee/react-native/android/notifee-json.gradle' line: 190

* What went wrong:
A problem occurred configuring project ':@notifee_react-native'.
> Cannot add task 'processRcDebugNotifeeJson' as a task with that name already exists.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**Comment by lkwjohn** [comment]
I have attempted using gradle 6.6 and recompiled it, the result is still the same. Wondering what could be happening that notifee 0.9.x works but not from 0.10.x and beyond

**Comment by mikehardy** [comment]
It is likely this commit, a great deal of "build" work when in to 0.10 in order to support licensing-by-flavor on android https://github.com/notifee/react-native-notifee/commit/d2e4d96fb826d7d2cd12ef297c8cc3dd8cfb7de5

I'd be happy to fix this but we can't reproduce. Obviously you can :-) - is there any way you could strip your project down to something that you could publish, and publish something that shows the problem on github?
