### ISSUE TITLE
iOS: Category doesn't work

### ISSUE THREAD

**Issue by mars-lan** [notifee/react-native-notifee#128]
### Environment
RN: 0.63.2
notifee: 0.12.1
iOS: 13.6

### How to reproduce?
1. Follow the [instructions here](https://notifee.app/react-native/docs/ios/categories) to `setNotificationCategories`
2. Invoke `displayNotification` using the `categoryId` registered in Step 1 (i.e. `post`)  
3. No "quick actions" shown with the notification

<img width="379" alt="Screen Shot 2020-08-23 at 3 38 24 PM" src="https://user-images.githubusercontent.com/24240669/90990482-bed80e00-e556-11ea-93f4-9a576729d675.png">

Note: Same issue with notifications scheduled using [Triggers](https://notifee.app/react-native/docs/triggers).

### Expected behavior
"Quick actions" to be shown with the notification

**Comment by helenaford** [comment]
Hey, I thought I ran into this issue the other day but I was doing something wrong. I've rechecked the docs and can see an issue in the last example where the category ids don't match up (one's `post` and one's `message`). Could you be doing that, by any chance? Otherwise, I'm not sure. I cleared out my pods and reinstalled the app to retest. It works for me on the same version 13.6 (iPhone 11). 
my code I have inside a function:
  ```
await notifee.setNotificationCategories([
    {
      id: 'post',
      actions: [
        {
          id: 'like',
          title: 'Like Post'
        },
        {
          id: 'dislike',
          title: 'Dislike Post'
        },
      ]
    },
  ]);

 await notifee.displayNotification({
    title: 'New post from John',
    body: 'Hey everyone! Check out my new blog post on my website.',
    ios: {
      categoryId: 'post'
    },
  });
```

![Screenshot 2020-08-24 at 14 28 50](https://user-images.githubusercontent.com/14185925/91050645-d971bc00-e616-11ea-8c66-26d2b48e2bba.png)

**Comment by mars-lan** [comment]
My bad. It was a typo indeed.
