### ISSUE TITLE
Local notification attachments not showing on IOS

### ISSUE THREAD

**Issue by davidokonji** [notifee/react-native-notifee#155]
Following the exact usage stated here https://notifee.app/react-native/docs/ios/appearance, the attachments don't show up on the IOS simulator, just a regular notification with a title and body.

Is there any configuration needed to be done on the IOS native for the attachments to show up?

Does it require a license to show up? 

Version: @notifee/react-native ^0.12.3

**Comment by melvinmt** [comment]
I’m having the same issue, iOS notifications are being sent but they are missing the attachments on iOS 14. Is this something that Notifee stopped supporting?

**Comment by melvinmt** [comment]
@mikehardy do you have any suggestions on this issue?

**Comment by mikehardy** [comment]
Sorry I don't have personal experience trying to add attachments and haven't tried to reproduce so I have nothing specific. It's not a specific license issue though, if you can show any notification then all notifications should work. It must be something about config, API usage, or a bug. Which? Unsure so far sorry

**Comment by helenaford** [comment]
I believe with the latest release (v0.13.0) it'll work. The issue is that with using `require('./assets/my-image.png')` it resolves to a url e.g. `http://localhost:8081/assets/assets/my-image.png` and prior to v0.13, remote urls were not supported. In release mode, they will be handled as a local file path.

**Comment by davidokonji** [comment]
@helenaford Tested the latest version (v0.13.0), it worked fine using an IOS asset file but did not work using a remote URL or a require('./imagepath').

**Comment by helenaford** [comment]
ah ok, strange, could you give more details on file you are trying to load, i.e. type & size. Or, maybe add it here, if you can. I've tested this myself and it works.

**Comment by helenaford** [comment]
mmm, how are you testing, are you viewing it via the notification tray or at the top when it first appears? 

Sometimes I can see how there's a slight delay on iOS 14.  If you are viewing it in the tray, what happens when you hit 'view'?

<img width="455" alt="Screenshot 2020-09-29 at 17 58 16" src="https://user-images.githubusercontent.com/14185925/94589942-d739f780-027d-11eb-8f86-943e72297155.png">
Have you tried with a real device?

**Comment by davidokonji** [comment]
@helenaford I just tested on an actual phone, running on IOS 14, viewing in the notification tray or at the top when it first happens, it does not show the asset when "view" is clicked it sets a focus on the notification with just title and body. testing on react native 0.63.2, is there any extra config that should be looked out for?

**Comment by helenaford** [comment]
ah I think I can see an issue with the release. Will push up a patch shortly.

**Comment by kennethjiang** [comment]
Having the same problem here. looking forward to an update.

**Comment by helenaford** [comment]
Update has been released (v0.13.1) with the fix.
