### ISSUE TITLE
iOS error ITMS-90078 when send to TestFlight and notifications stop working

### ISSUE THREAD

**Issue by czuiko** [notifee/react-native-notifee#167]
We integrated the notification into iOS using Notifee. Everything works on a physical device connected to a computer, notifications are visible.

When we download the application from the TestFlight, the notifications do not work, and Apple sent a message:

> ITMS-90078: Missing Push Notification Entitlement - Your app appears to register with the Apple Push Notification service, but the app signature's entitlements do not include the 'aps-environment' entitlement. If your app uses the Apple Push Notification service, make sure your App ID is enabled for Push Notification in the Provisioning Portal, and resubmit after signing your app with a Distribution provisioning profile that includes the 'aps-environment' entitlement. Xcode does not automatically copy the aps-environment entitlement from provisioning profiles at build time. This behavior is intentional. To use this entitlement, either enable Push Notifications in the project editor's Capabilities pane, or manually add the entitlement to your entitlements file. For more information, see https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/HandlingRemoteNotifications.html#//apple_ref/doc/uid/TP40008194-CH6-SW1.
> 
> After you’ve corrected the issues, you can upload a new binary to App Store Connect.

Is it error make any impact or not?

What we did:
In Xcode and developer portal all required checkboxes have been checked.
We sent the build again, but the message is still old.

Help me please how to solve the problem with Apple and notifications, thanks

**Comment by mikehardy** [comment]
Hi @czuiko - it is important to be precise in terms in this area. Apple's definition of "Push Notifications" here maps most cleanly to firebase's definition of "cloud message". I mention that because a "push" notification is actually a piece of data sent from cloud to device.

Notifee however is a *local* notifications package. It handles calling device-local APIs and does not handle message delivery or receipt from cloud systems.

Anything to do with Apple Push Notifications, so support for same is out of scope for this package.

That said, if your app relies on cloud messages / apple push notifications, and they are not working, and you are getting a warning about missing entitlements you should carefully examine your project setup for all build types (debug, release targets / dev, app store profiles etc) as you'll have to make sure those are correct before you will get cloud messages

As cloud messaging is out of scope here, I'm going to close this, but if there is a problem with the behavior of the Notifee module when you call one of it's APIs please do open a new issue to let us know
