### ISSUE TITLE
Build error for ios

### ISSUE THREAD

**Issue by nicocolascrete** [notifee/react-native-notifee#195]
Hello,

I have trouble with notifee on our build machine. We use fastlane and we have this trouble for ios build. When the build gets to the Notifee package step, we get this error.

> Failed to compile bundle: /var/folders/fb/3zsk_std7nd_62hw_00hd0ssscgz69/T/NotifeeCore0kwtjlk6/NotifeeCore.armv7.xar 
> Clang: cd /var/folders/fb/3zsk_std7nd_62hw_00hd0ssscgz69/T/tempyu28c5_a
> ['/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang', '-cc1', '-triple', 'thumbv7-apple-ios10.0.0', '-emit-obj', '-disable-llvm-passes', '-faligned-alloc-unavailable', '-target-sdk-version=14.0', '-target-abi', 'apcs-gnu', '-Os', '-mllvm', '-arm-bitcode-compatibility', '-mllvm', '-fast-isel=0', '-x', 'ir', '5', '-o', '5.o']
>     -= Output =-
>     error: Invalid record
>     1 error generated.
>     Exited with 1

Someone has an idea to how fix it? For informations we don't have this issues localy on our mac.
Thanks, for you help guys!

**Comment by mikehardy** [comment]
That's a new one, is there a way you could attach the entire build log?
What is 'thumbv7-apple-ios10.0.0' - I'm not sure what that thumb target is?
What version of Xcode are you using?
What machine architecture is the build machine?
Do you run `npx react-native-clean-project` prior to your build in order to make sure there is no random Xcode cache incoherency going on?

If you can find a way to reproduce it with a simple minimal repro that could help, here's a skeleton: https://github.com/mikehardy/rnfbdemo/blob/master/notifee-demo.sh

**Comment by nicocolascrete** [comment]
Our build machine is a mac mini ( 2018 ) on macOs Catalina 10.15.7 and XCode 11.5.
Yes I clean the XCode project.

I update to last XCode ( 12.2 ) and he seems good now. So it had to come from the xcode version. I confirm this monday.
Thanks!

**Comment by mikehardy** [comment]
That could make sense - we are definitely all Xcode 12.x at this point because we're using ios14 APIs for Firebase maintenance (a separate module we work on) and our general position (matching the general react-native position) is that only current stable version of Xcode is supported. Thanks for reporting back and I'm glad it's working for you now!
