### ISSUE TITLE
Firebase-related?

### ISSUE THREAD

**Issue by hmazer** [notifee/react-native-notifee#2]
Is this module related to r-n-Firebase or not?
Can I, for instance, register to fireabase nototification topics without it ?

**Comment by Salakar** [comment]
Separate to RNFirebase. RNFirebase Messaging already allows you to register to messaging topics. Messaging is not notifications.

This library will allow you to create local notifications without FCM, or make richer notifications from an FCM message if using alongside RNFirebase Messaging.

**Comment by matamicen** [comment]
@Salakar So in order to implement PushNotifications I can use FCM messaging with notifee ? if the answer is yes, If the app is installed and is in Foreground, background or even not launched Do I can still receiving the push Notifications ? Do I have to still using APNS certificates to everything works on the iOS side or FCM Messaging replace APNS in this case?  Sorry to many questions but I don't understand the Arquitecture of all of this. Thanks! :)

**Comment by Salakar** [comment]
> If the app is installed and is in Foreground, background or even not launched Do I can still receiving the push Notifications ?

For Android on Notifee this works if the app is in the foreground, background & or is quit, so you will always get the notification sent to JS land.

For iOS on Notifee, due to platform limitations this only works in some scenarios (mainly around if the APNS message is sent with `content-available`) - but we are looking into possible aways around this e.g. via a `UNNotificationContentExtension` - but so far most of our time has been spent getting Android ready for alpha release so it's too early to say much about iOS.

**Comment by matamicen** [comment]
@Salakar So Do I still have to hava APNS certificate in order to FCM sends the meesages? The Alpha release will include Foreground/Background for iOS at least? thanks.

**Comment by matamicen** [comment]
@Salakar To be more clear in our situation, We are sending right now push from our backend Server and receiving the push with Aws amplify pushNotification (RN), if we just uninstall Aws amplify push and install notifee it will work? and avoid using Firebase Messaging? (I told you may be I don't understand yet the Total Arquitecture haha :)

**Comment by Ehesp** [comment]
Hey, a guide has been written up about FCM integration: https://notifee.app/react-native/docs/integrations/fcm
