### ISSUE TITLE
Catalyst Support

### ISSUE THREAD

**Issue by ajnozari** [notifee/react-native-notifee#215]
I'm trying to build an app locally for MacOS, but I'm running into a bit of an odd issue. 

`
Building for Mac Catalyst, but linking in dylib built for iOS Simulator
`

I'm fairly certain I either need to tell it to NOT link Notifee for MacOS or I'm not configuring it right to build the x86_64 portion of it.  If this needs a PR submitted, just point me in the direction of how to add this support in and I'll at least take a crack at it.

Thank you in Advanced,

Andre

**Comment by mikehardy** [comment]
I think this may very well be a duplicate - in a way - of #162 - which is requesting arm64 support

Why is it a duplicate? Because part of the problem with the current packaging of Notifee for Xcode is that it is done in a way where we can't include multiple x86 slices (only one is allowed, and we use it for the simulator, thus when you try a catalyst build which is normally for an x86 processor it doesn't work), and we can't include multiple arm64 slices (only one allowed, we use it for real ios devices but that means Apple Silicon simulators don't work)

We are working on that right now and should have results shortly, you should subscribe to that issue and when I have a test build available it will solve your problem at the same time as we'll start delivering an .xcframework that has catalyst builds for x86 and arm64 along with the simulator builds for x86 and arm64 and of course real device arm64 slices.

**Comment by ajnozari** [comment]
Oh apparently I need to up my search powers

**Comment by mikehardy** [comment]
No worries at all - it's not a straightforward dupe at all, but I am literally reviewing the pull request for it at the moment and we have maccatalyst x86_64 slices in there, so it should happen shortly. Cheers

**Comment by mikehardy** [comment]
Mac Catalyst builds should work now in the linked PR, and there are instructions to test-integrate it on the linked issue - here is a deep link to the comment since I would love it if you tried it and posted feedback 😄  https://github.com/notifee/react-native-notifee/issues/162#issuecomment-747955777
