### ISSUE TITLE
How can I group notifications when app in background?

### ISSUE THREAD

**Issue by saumaychainflux** [notifee/react-native-notifee#245]
I want to show grouped notifications while app is in background or quit state. 
I am using '@react-native-firebase/messaging'.

This is how I am trying to do
```
messaging().setBackgroundMessageHandler(async message => {
  console.log('Message handled in the background!', message);
  notifee.displayNotification({
    title: message?.notification?.title,
    body: message?.notification?.body,
    android: {
      channelId: message.data.offer_id,
      groupSummary: true,
      groupId: message.data.groupId,
      groupAlertBehavior: AndroidGroupAlertBehavior.SUMMARY,
    },
  });
})
```

**Comment by helenaford** [comment]
Hmmm, it should be OK to do that.... do you have some log output so I can see what the final notification object is?  Also, you might want to catch any validation errors to rule that out.

**Comment by saumaychainflux** [comment]
The grouping isn't happening. All notifications are seen as seperated cards.
![Screenshot 2021-02-11 at 5 06 20 PM](https://user-images.githubusercontent.com/75999197/107631715-7854a800-6c8b-11eb-96fa-5a6675d05188.png)

**Comment by helenaford** [comment]
sorry, i mean log output of the notification created from notifee. e.g.

```
messaging().setBackgroundMessageHandler(async message => {
  console.log('Message handled in the background!', message);
  try {
  const notification = {
    title: message?.notification?.title,
    body: message?.notification?.body,
    android: {
      channelId: message.data.offer_id,
      groupSummary: true,
      groupId: message.data.groupId,
      groupAlertBehavior: AndroidGroupAlertBehavior.SUMMARY,
    },
  };
  console.log('notifee notification', notification);
  await notifee.displayNotification(notification);
} catch(e) {
   console.log('an error occurred ', e)
}
```
})

**Comment by helenaford** [comment]
Also, can you rule out that notifee local notification one is showing rather than firebase message?

**Comment by saumaychainflux** [comment]
> Also, can you rule out that notifee local notification one is showing rather than firebase message?

How can I rule that out?
Bcoz setBackgroundMessageHandler will trigger the firebase notification, won't it?

**Comment by mikehardy** [comment]
The most effective way to reason about it is for you to post JSON directly to FCM via the FCM REST API, then to paste the JSON you posted here (minus device tokens etc)

Then we may see exactly what is being triggered and why

The short answer is: if you include a 'notification' payload in your JSON, then firebase SDKs will show a notification without any react-native-firebase or notifee code executing. If you do not include 'notification' payload (i.e., it is a 'data-only' / 'silent push' notification) then you can rule out that firebase is showing the notification

**Comment by saumaychainflux** [comment]
@mikehardy Thanks!
I am sending data-only payload now. But now, no notification is shown in pane.
 @helenaford  this is the response I am getting
 
![Screenshot 2021-02-11 at 10 31 48 PM](https://user-images.githubusercontent.com/75999197/107670637-efecfc00-6cb8-11eb-88da-ac60bce9e7b4.png)

**Comment by mikehardy** [comment]
You are still sending a notification block, when present with a "data" block this is called a "mixed" notification in FCM terms

The documentation upstream on the firebase site from google about receiving messages in ios and android and which types of FCM are handled by which things are very instructive. I can only recommend memorizing them, and I'm not joking! Very important to understand the layers underneath react-native-firebase (and notifee) before attempting to build on them.

You are logging things but you do not indicate if your handler is triggered at all. I suppose with a mixed FCM, based on the FCM documentation, that the background message handler did not fire, and since the notification is empty now, nothing was posted, so nothing will happen.

Note separately that *if* you go to data-only notifications you will be subject to the "unreliability by design" problem that people have on iOS, which is that even with the "content-available" key specified, Apple may throttle you at the APNs level, and/or the device may throttle you at the FCM delivery-to-device level and you may never get those messages, so you should not make them a critical part of your app.

*if* you go the other way and use "notification" payloads (for more reliability in delivery) then the underlying firebase SDKs handle the messages and you will then have a different set of constraints, since notifee code does not execute.

**Comment by saumaychainflux** [comment]
@mikehardy Okay, if I'm sending data-only payload, I'm getting notifee's notification.
Back to my question, how to group them?

**Comment by mikehardy** [comment]
Once notifee is in complete control of the notifications posted, it should function exactly as https://notifee.app/react-native/docs/android/grouping-and-sorting#grouping indicates - is it not? That would be surprising. Even if you hard code a group id in there they do not group? That would be an unexpected result for sure

**Comment by helenaford** [comment]
If you're not getting any notifications, I'd check the channel is created and you can send any notification with notifee with the same channelId outside of any event listener. Then, add back in the grouping... and then finally put it back in the backgroundMessageHandler.

**Comment by helenaford** [comment]
@saumaychainflux please re-open if you are still experiencing the issue.
