### ISSUE TITLE
iOS Background Notification did not display

### ISSUE THREAD

**Issue by univalchemist** [notifee/react-native-notifee#266]
I use this notifee to display a custom notification with image, but it sometimes shows notification but sometimes does not show on background mode.
I tested it several times but same issue.
It works fine on foreground but if app is killed or on background status, it does not work properly.

**Comment by mikehardy** [comment]
Hi there! What platform (iOS, Android?), what version of Notifee, and what is the JSON you send (I am assuming you are sending cloud messages)?

Of note even before getting that information - on iOS specifically - data-only background notifications are unreliable by design of the operating system. iOS does not guarantee delivery of data-only notifications, they are in fact dropped on purpose in several conditions (low battery percentage, low power mode, background refresh is off, already sent too many, your app used a lot of power budget already, device temperature is high - those are just a few I can think of).

If these are cloud messages and they are data only, and delivery in the background is a vital part of the app, it may be that you are not able to use data-only messages as a design choice

**Comment by univalchemist** [comment]
`"@notifee/react-native": "^1.2.0-0"`
platform: iOS as I titled.
`{
    "to":  "fcm token",
    "data": {
        "title": "here is titile",
        "body": "body message,
        "icon": "extra icon url",
        "url": "...",
        "msg_id": 0,
        "influencer_id": "..."
    },
    "content_available": true
}`
Yes, cloud message. I use firebase rest api and python libray
`https://fcm.googleapis.com/fcm/send`


So there is no way to use this notifee on background mode, but the documentation says it will work on background as well,
that's why I purchased and tried to use it on my app.

**Comment by mikehardy** [comment]
I use it in the background successfully, with reasonable delivery rates, but platform limitations are something we and anyone has to manage. I don't use it for features where guaranteed delivery is a requirement.

**Comment by mikehardy** [comment]
I also asked internally if there are any new ideas on the issue, I know there is work on an iOS notification extension, and I'm not too familiar with it but it may be aimed at handling background cases more reliably

**Comment by univalchemist** [comment]
The documentatioin needs to describe correctly that iOS background notification does not have guarantee with this library.
So I would not try to use this and wasted my time.

**Comment by helenaford** [comment]
Hi, you can now use Notifee with remote notifications in the latest release (https://notifee.app/react-native/docs/ios/remote-notification-support). This should improve reliability of sending notifications in the background but again it's not something we can guarantee. I don't think you will find any notification library that can as it is limited by the device capabilities.

**Comment by itsthisjustin** [comment]
> Hi, you can now use Notifee with remote notifications in the latest release (https://notifee.app/react-native/docs/ios/remote-notification-support). This should improve reliability of sending notifications in the background but again it's not something we can guarantee. I don't think you will find any notification library that can as it is limited by the device capabilities. 

Excuse my ignorance but if this is just now possible as of 7 days ago, how was this ever working before for background push?

**Comment by mikehardy** [comment]
"background push" - what *exactly* is that? do you mean, a data-only FCM? I just want to make sure we're talking about the same things as this stuff is very precise, and that's the difficult case.

The way it was working before was unreliably. It *did* work under quite a few conditions, but it also did not work under quite a few conditions. 

In order to get more reliable notifications you would include a notification block so it wasn't just data-only, but then you couldn't use all the notifee styling etc, because the SDK posted the notification without giving you a chance to process it.

I believe - which is to say @helenaford please correct me if I'm wrong! - that now you can send a notification block now (much more reliable background delivery!) and still get Notifee styling / messaging behavior from this extension.

**Comment by itsthisjustin** [comment]
> "background push" - what _exactly_ is that? do you mean, a data-only FCM? I just want to make sure we're talking about the same things as this stuff is very precise, and that's the difficult case.
> 

ah possible this isn’t relevant then? We have THE most unreliable background pushes. Badge count always updates. iOS banners don’t always show though. Can’t figure it out. I was hoping this was our silver bullet.

**Comment by helenaford** [comment]
@itsthisjustin I think we're struggling to understand if your reference of a `background push` is a data-only message or a notification message. 

And, as @mikehardy mentioned, with this new feature you can send notifications much more reliably using remote messages with a `notification` property) , and don't have to worry about if the app will wake up.

**Comment by mikehardy** [comment]
the only way to help in that case ("unreliable background pushes") is to get nitty-gritty and see the actual JSON posted and the code handling it, but in general if you are sending data-only background messages (using the "content-available" flag on iOS) then they are not reliable, no. They *can* work, but must only be used for situations where delivery failure is okay as they are designed (by Apple) to be a "this would be nice if you pre-cache content, but no big deal" feature, not a reliable messaging system

messages with notification blocks though - that's another thing. They are still not 100% but now they should delivery in most cases and only not deliver in a few, the inverse of data-only. If you are having fundamental reliability problems with messages sent that have notifications, there may be something to look at, at least to understand more

**Comment by Markuson** [comment]
Looks like I'm also not able to receive any data-only notification while app is in background on iOS. It was kind of working some months ago (not reliable but working some times... but stil not good enough), but now, updating Notifee to the last version, looks like it's not working anymore....

My company is about to launch notifications during this month, and now i've found notifications are not reliable on iOS. We stick to this library and we pay for that and now we found that is not reliable... It will be a complete mess for me and for my company... is there anything I could do to solve this issue? I'm completely desperate to make this work as soon as posible.

while on foreground state data-only messages are received well, and normal notifications (I mean non data-only ones) are working too in both cases background and foreground.

**Comment by mikehardy** [comment]
data-only notifications are specifically marked on iOS as "content-available" - the clue to their reliability is in those words and in the iOS documentation on the Apple developer site. They are just notifying the app that there is some fresh content available, and *if* it's possible it would be nice if the app would pre-fetch it and cache the content. Delivery is never guaranteed.

I think if you want guaranteed delivery you *must* use notification blocks, and then for branding / interactive purposes you will want a notification extension so you can process the notification prior to display.

**Comment by Markuson** [comment]
what do you exactly refer for notification blocks and notification extension?

thanks.

**Comment by mikehardy** [comment]
@Markuson meaning no offense but 

1) if:

> My company is about to launch notifications during this month, and now i've found notifications are not reliable on iOS. We stick to this library and we pay for that and now we found that is not reliable... It will be a complete mess for me and for my company.

2) ...and you need further definition for:

> what do you exactly refer for notification blocks and notification extension?

3) ...then I can only conclude that you should do some research and documentation reading as soon as possible. These are *vitally* important concepts for any company that is intending to rely on notifications on iOS devices to understand. You will have great difficulty with your solution until you can answer your own question patiently explaining it to me instead of me explaining it. It is worth the time investment!

That said:

- "notification blocks" - cloud messages contain JSON payloads. The JSON payload may contain a "notification" block, and a "data" block. Typically cloud messages with JSON payloads that only contain data blocks are referred to as "silent push notifications" or "data-only messages". They are unreliable as I described above. Useful in many many cases, but not 100% reliable. If you add a notification block to your payload then your message is handled much differently by iOS and Android.

You can start reading here but there's lots of information all over the web https://firebase.google.com/docs/cloud-messaging/concept-options

- "notification extension" - if you use a notification block in your cloud messaging JSON payload you will get more reliable delivery (still not 100%, but much much more reliable). But now you have a second problem which is that on iOS the firebase-ios-sdk and iOS operating system will control what the message looks like by default. This is typically an unbranded notification that will simply open your app when tapped and call an API handler you specify indicating the user tapped a notification (optionally with some data provided to the API handler you specify such that you may handle this tap in useful way). That's a good start but if you want the notification to have actions in it or contain images or be non-default in any way then you need to implement a "Notification Extension" which is a new chunk of native iOS code that the message payload passes through prior to showing the notification. You get the chance to alter the appearance that way. This is all documented here https://notifee.app/react-native/docs/ios/remote-notification-support

Good luck with your project!

**Comment by mikehardy** [comment]
Okay - it sounds like the notification extension I mention will be the path then - if I correctly understand the business requirement "[we need] to be able to 'catch it' and have control on what is launched what not to the notifications tray for the user [etc]"

That's the exact use case the extensions are for: control over the notifications in combination with use of notification block for reliable delivery.

It is unfortunately not the easiest path - it involves native code - but it is the reality of cloud messaging on iOS

**Comment by Markuson** [comment]
I guess... But it will only do the job for iOS right? For Android it won't be a solution.

For us, data-only notifications was the best way cause we will receive the notification "internally" and then we will launch the notification to the tray using the corresponding body and title and/or the corresponding icon. We do not need any action more than opening the app (for now...) When we press the notification. Also, receiving data-only notification allows us to check if the notification is already launched and not launch it again in that case. Because the cloud we are working just launched the notifications when the condition is accomplished and don't look for anything more.

**Comment by mikehardy** [comment]
background delivery on android is much more reliable

**Comment by Markuson** [comment]
Yes, I can see that. The thing is that for now we cannot choose data-only message for Android users and notification message for iOS users... We should use just one of the options for all users. So that makes things harder for us.

Anyway. Thanks for your answers. It's been quite interesting discussion for me and I guess it will answers some more questions to other users looking for help.
