### ISSUE TITLE
AndroidImportance is not updating when calling notifee.createChannel again.

### ISSUE THREAD

**Issue by shubhamdeol** [notifee/react-native-notifee#281]
I am creating a notification channel like this. I can see in my phone' setting channel is being created with notifications toggle on.
```js
notifee.createChannel({
              id: 'addEntry',
              name: 'Add Entry',
              importance: AndroidImportance.DEFAULT,
            })
```

On some button press I want to update the channel information to 

```js
notifee.createChannel({
              id: 'addEntry',
              name: 'Add Entry Updated',
              importance: AndroidImportance.NONE,
            })
```

But I can see from my App's setting toggle is still `ON` but name is updated to `Add Entry Updated`. this confirms that my channel is getting updated but importance is not updating. 

- Platform: Android
- RN Version: 0.63
- Notifee version: 1.3.0
- Build Type: debug build

**Comment by shubhamdeol** [comment]
I also tried first deleting the channel and re creating the channel with same Id, Still this does not seem to work

```
     await notifee.deleteChannel('addEntry');
     await notifee.createChannel({
        id: 'addEntry',
        name: 'Add Entry',
        importance: AndroidImportance.NONE,
      });
```

**Comment by mikehardy** [comment]
Easy answer first: I believe the license page details exactly what the restrictions are with regard to license checking etc https://notifee.app/frequently-asked-questions - You can do debug mode builds that are full-featured for a full test, but not release builds, no.

More difficult answer: what you want to do is not possible. 

> After you create a notification channel, you cannot change the notification behaviors—the user has complete control at that point. Though you can still change a channel's name and description.

https://developer.android.com/training/notify-user/channels contains the details

You get one chance to create a channel and after that you can manage name and description and that's it - this is because developers abused this in the past, so Android as a platform put the control in the user's hands and took it from the developers.

If you need functionality where the user increases priority somehow you either need to educate the user on how to manage notification channels and open the settings, or have different channels with different priorities and route the notifications to the correct channel

**Comment by shubhamdeol** [comment]
Thanks
