### ISSUE TITLE
[Android, MIUI] Notifications will be displayed as silent

### ISSUE THREAD

**Issue by bartekkaminski** [notifee/react-native-notifee#30]
**Prerequisites:**
Latest versions packages
MIUI Global 11.0.3 (Android 10)

**Steps to reproduce:**

index.js
```
// Register background handler
messaging().setBackgroundMessageHandler(async remoteMessage => {
    // Create a channel 
    const channelId = await notifee.createChannel({
        id: 'PIKS',
        name: 'PIKS',
        lights: true,
        vibration: true,
        importance: 4,
        visibility: 1
    });
    // Display a notification
    await notifee.displayNotification({
        title: 'Notification Title',
        body: 'Main body content of the notification',
        android: {
            channelId,
            importance: 4,
            visibility: 1
        },
    });

    console.log('Message handled in the background!', JSON.stringify(remoteMessage));
})
```

Server
```
var message = {
    token: tokenSnapshot,
    notification: {
        title: "Title",
        body: "Body",
    },
    android: {
        priority: 'high',
        notification: {
            sound: 'default',
            priority: 'high',
            visibility: 'public',
            channelId: 'PIKS'
        },
    },
};
```

**Result:**
- notification is silent
- no vibration
- no sound
- nothing appears on the lock screen

In the attached picture Channel is created in this way

![Screenshot_2020-04-14-12-51-45-501_com android settings](https://user-images.githubusercontent.com/23075165/79217225-c53ed680-7e4e-11ea-9352-a581db73a07c.jpg)

The notification is only visible when the user checks if there is any new notification

**Expected result:**
- vibration
- sound
- notification on lock screen

**Comment by Ehesp** [comment]
There's a few issues here:

1. You're sending an FCM payload with a `notification` object, therefore FCM will display the notification.
2. You're setting a channel on the FCM payload, however creating a channel in the background handler. FCM will handle the message before the background handler is run (so there may be no channel).
3. If you want to display a notification with Notifee from FCM, send a data-only payload (see [docs](https://notifee.app/react-native/docs/integrations/fcm)).
4. You should be creating a channel when the app opens, not on a background event.

Take a look at https://rnfirebase.io/messaging/usage too. I'd recommend sending only data-only messages via your server if you want to fully use Notifee, otherwise it's the native SDKs which will display remote notifications.

Also, you're using direct number values in places where we recommend using the exported interfaces, e.g:

```
import notifee, { AndroidVisibility } from '@notifee/react-native';

const channelId = await notifee.createChannel({
  id: 'secret',
  name: 'Secret Notifications',
  visibility: AndroidVisibility.PUBLIC,
});
```
