### ISSUE TITLE
AndroidStyle.BIGTEXT unexpanded at first

### ISSUE THREAD

**Issue by Minishlink** [notifee/react-native-notifee#317]
Hi,

When setting a style `AndroidStyle.BIGTEXT`, would that be possible to make the notification unexpanded by default? Currently it always shows as expanded at first. Is it something that we could implement in this library or does it depend on Android?

Thanks

**Comment by helenaford** [comment]
hey, good question.  There's no official Android API to do so, I think that's probably been a conscious choice to let the user have control over it rather than developers.  But, certain channel settings such as setting importance to high may encourage the device to auto expand the notification (would have to test this).

**Comment by helenaford** [comment]
@Minishlink if you need unexpanded by default (realised I read it as the other way), my answer still applies - there's no control over this I believe. It may also depend if your notification is first in the tray or not. I'm going to close this as there's nothing we can do, unfortunately. 

<img width="353" alt="Screenshot 2021-06-01 at 15 45 47" src="https://user-images.githubusercontent.com/14185925/120343213-707b4b00-c2f0-11eb-98d2-eb0301e3f846.png">

**Comment by Minishlink** [comment]
@helenaford I see, thanks for looking into it!
