### ISSUE TITLE
 CocoaPods could not find compatible versions for pod "RNNotifee":

### ISSUE THREAD

**Issue by vtn-dev-sameer** [notifee/react-native-notifee#34]
Hi,

Issue after installing react native plugin and try to install pods.

 [!] CocoaPods could not find compatible versions for pod "RNNotifee":
  In Podfile:
    RNNotifee (from `../node_modules/@notifee/react-native`)

Specs satisfying the `RNNotifee (from `../node_modules/@notifee/react-native`)` dependency were found, but they required a higher minimum deployment target.

**Comment by mikehardy** [comment]
ios9 is not supported, I think you have to do ios10 or above https://notifee.app/react-native/docs/environment-support#support-table

I'm one of the pathetic types that only has an iOS tablet form factor on a device that cannot be upgraded past iOS9, so this affects me personally but last time I looked at stats, dropping iOS9 is valid because there are not many like me anymore, and the industry has agreed, with facebook themselves already doing so with their apps, and react-native in general dropped iOS9 for react-native 0.63.

**Comment by mikehardy** [comment]
(of course if I guessed wrong and  you're already specifying a target of 10 or above please reply and this obviously should be reopened!)

**Comment by mectos** [comment]
@mikehardy 
Hello, I have the same issue but I can't get it fixed.
I changed (in Xcode preferences) the iOS version from 9.0 to 10.0, though it still doesn't work for some reason.

Thank you in advance :)

**Comment by mikehardy** [comment]
I think it's a Podfile change. Specifically like this https://github.com/invertase/react-native-firebase/blob/master/packages/template/project/ios/Podfile#L1

**Comment by mectos** [comment]
Worked thank you!
