### ISSUE TITLE
Feature request: Schedule notification with AlarmManager on Android

### ISSUE THREAD

**Issue by Lolinpiko** [notifee/react-native-notifee#43]
Do you plan on integrating an option to schedule local notification using the AlarmManager and allowing us to bypass the Idle mode ?

https://developer.android.com/reference/android/app/AlarmManager

**Comment by Ehesp** [comment]
Hey

Yeah we're going to be using https://developer.android.com/topic/libraries/architecture/workmanager rather than AlarmManager for Android scheduling, since it wraps AlarmManager on older devices.

We have this working locally for Android, but we're still figuring out the API compatibility with iOS.

**Comment by helenaford** [comment]
Closing this in favour of #36.
