### ISSUE TITLE
[iOS] getInitialNotification doesn't work when receiving notification when app is quit

### ISSUE THREAD

**Issue by gabrielbull** [notifee/react-native-notifee#89]
# Bug report

## Steps to reproduce:

`getInitialNotification` does not work when the notification is shown while the app is **quit**.

```jsx
import notifee from '@notifee/react-native'

notifee.getInitialNotification().then(initialNotification => {
  if (initialNotification) {
    console.log(initialNotification)
  }
})
```

It does however works if I receive the notification while the app is open and display it using `notifee.displayNotification`, then quit the app and then click on the notification.

I use `setBackgroundMessageHandler` from [react-native-firebase/messaging](https://rnfirebase.io/messaging/usage#message-handlers) but it does not seem to have any effect. For instance, if I do this:

```jsx
import messaging from '@react-native-firebase/messaging'
import notifee from '@notifee/react-native'

messaging().setBackgroundMessageHandler(async remoteMessage => {
 notifee.displayNotification({ title: "Fake notification", body: "This is not the real notification" })
})
```

I never see the fake notification.

**Comment by menafkasap** [comment]
I am facing the same issue.

I want to use Notifee for incoming calls, Android app is done and runs properly but I have this problem in my iOS app.

In iOS `setBackgroundMessageHandler` works when the app is running in the background but it does not work for notifications when the app is quit. (or silent notifications because I don't want to show them twice) 
Actually I know the app will not be launched when it has a notification in the quit state if we don't use PushKit, VoIP etc.

https://stackoverflow.com/questions/19068762/will-ios-launch-my-app-into-the-background-if-it-was-force-quit-by-the-user

@Salakar is said in #93 
> Thanks for the report - this is 100% a duplicate of #89 of which I'll hopefully have a fix in for by the end of the week.
> 
> Let's track on #89. Thanks for raising this issue 🎉

I don't think we can solve this issue easily with a fix. We can't launch the app and we can't run `setBackgroundMessageHandler` with a notification when app is quitted. 

I'd love to hear a solution other than VoIP.

PS: We are waiting for fullscreen intent notifications on Android 🙏

**Comment by mikehardy** [comment]
There is a very limited set of things that will wake up your app in iOS from force-close by design

Not even https://github.com/transistorsoft/react-native-background-fetch can do that. All you can do is post a notification and hope your user responds to it. If your app is useful to them, they will, if not, the code sleeps
