### ISSUE TITLE
Is possible to create Media Style Notification in android notifications?

### ISSUE THREAD

**Issue by SaeedZhiany** [notifee/react-native-notifee#9]
![image](https://user-images.githubusercontent.com/13766432/73265453-3ffe3b00-41ea-11ea-8a51-6119faab4acf.png)

The image is a random image from google search. 

Can we create such notifications using Notifee?

**Comment by Ehesp** [comment]
This sort is a [Media Style Notification](https://notifee.app/react-native/docs/android/styles#media), which right now isn't supported. We're prioritising triggers (e.g. Schedules) & iOS support first.

**Comment by sampsonjoliver** [comment]
While in Alpha, it would be great to see some high-level roadmaps on features like these (schedules, initial iOS support, Android Media notifs, etc).

I think there's a decent number of RN devs that are *preeetttyy* unsatisfied with the Android Media Style Notification libraries out in the world right now.so we're quite keen to throw our money at a solution as soon as it becomes available :)

**Comment by VivienTournie** [comment]
Any update on this one ? WIP ? :)

**Comment by VivienTournie** [comment]
Still no update ?
I do know you have other things to work on and your time isn't infinite. I just would like some information on this request which is almost 1 year old.

Thanks.

**Comment by Ehesp** [comment]
It's not possible to just "create" one, which is why it's not been done. You need actual media playing on the device which returns a token, and this is fed into a notification to display things. We could expose that token feed, however it's not much use without a way for users to control media. 

We have taken a look into some of the media libraries but none support returning the token.

**Comment by VivienTournie** [comment]
Sorry I was not specific enough in what I need in this request.

My goal is to play a streaming song from (for example) Napster API from trigger notification. Those are .mp3 remote files (30sec).

According to Helena : "For remote file support when implemented, the plan is that you would be able to pass in a url that points to an audio file and the API will be able to attach it to the notification".
See https://github.com/notifee/react-native-notifee/issues/132#issuecomment-683655652

iOS is already implemented : https://github.com/notifee/react-native-notifee/issues/132#issuecomment-699127332

What about Android ?

**Comment by helenaford** [comment]
The remote file support was referring to iOS. For Android, I believe it would require a media style notification 🙁

**Comment by VivienTournie** [comment]
Oh that's a disaster... I bought a Notifee license especially for this part of the lib because Notifee was supposed to support this..

**Comment by VivienTournie** [comment]
> It's not possible to just "create" one, which is why it's not been done. You need actual media playing on the device which returns a token, and this is fed into a notification to display things. We could expose that token feed, however it's not much use without a way for users to control media.

I believe you're talking about MediaSession token ? (cf. [Android Developers blog on "Playing nicely with media controls"](https://android-developers.googleblog.com/2020/08/playing-nicely-with-media-controls.html))

The steps to create a [media browser](https://developer.android.com/guide/topics/media-apps/audio-app/building-a-mediabrowserservice) service are :
- Create and initialize the media session
- Set the media session callback
- Set the media session token

My understanding is that a media session can be created then can be "paused" (called "inactive" in Android documentation), putting a Play action into the PlaybackState associated with the session. Isn't it possible to create the session, associate a media (audio, video), just to create the mediaBrowser Service, then when the notification triggers,[ use the playback action to activate the media session](https://developer.android.com/guide/topics/media-apps/mediabuttons#restarting-inactive-mediasessions) and play the media ?

> We could expose that token feed, however it's not much use without a way for users to control media.

By default Android is now using ExoPlayer to play audio and video both locally and over the Internet. On my react native project i'm using [react-native-track-player](https://github.com/react-native-kit/react-native-track-player) to play remote .mp3 files and control media. From what I understood it uses the same callbacks structure than Android ExoPlayer/MediaPlayer (onPlay(), onPause(), and onStop(), ...).
Could we imagine using this player as media controller ?

I'm not Android native developer so sorry if my propositions aren't realistic. I'm trying my best to help you find a solution .. :)

**Comment by Ehesp** [comment]
That's possible yes, however we need access to that token created from the media player. Last time I checked the track-player library didn't support it

**Comment by VivienTournie** [comment]
They seem to be using media session token [for some things](https://github.com/react-native-kit/react-native-track-player/search?q=session+token). Idk if this could be reproducible/usefull for Notifee

**Comment by Ehesp** [comment]
Ok so I spoke with the author of the library; they create their own notifications since it's required to keep the music service running (foreground notifs). I'll have a look through the source code and see if we can hook into those created notifications.

**Comment by mikehardy** [comment]
@Ehesp maybe related, there was a separate request for Notifee to be able to handle interaction on notifications that were automatically displayed when firebase cloud messages included a notification payload. I'm not sure if that is implemented yet but the reason I comment is that it seems like it might be generic at design level - "allow specification via configuration of some thing (a message id pattern or something?) that let's notifee know that it should pay attention to an otherwise-external notification (FCM notification payload, music player foreground service notification, etc)"

**Comment by VivienTournie** [comment]
@Ehesp Have you been able to take a look ?

**Comment by VivienTournie** [comment]
Any news on this request ? Sorry to post again, but without a public roadmap, it's hard to know where you're at or what you're working on right now.

**Comment by helenaford** [comment]
No problem. We understand this is the main way you can contact us and get your questions answered. There's currently a lot of work being done behind the scenes to speed up deployment and testing which will have an immense impact at the speed we can push out features like this. I can sync up with Elliot and get back to you. Thanks for being patient.

**Comment by VivienTournie** [comment]
@helenaford Have you been able to sync up with Elliot on this request ? This request has been pending for 1 year now, which is huge in the mobile app world :(

**Comment by helenaford** [comment]
Yes, think I've got a solution. I've been working on it for the last 2 weeks seeing how we can integrate with react-native-track-player. It's not easy 😆 The first think I looked at was getting the session token out, so you could use it when create a notification with Notifee but doesn't seem possible, and tbh it's probably best it's left on the native side. 

The other thing and I think how we can get it to work initially is to create what looks like a media style notification but without the session token. Then when the user clicks play, you can call TrackPlayer.play() where their notifications will take over, if that makes sense.

I'm aware this will need some testing, and feedback. 

Didn't have time to make the artwork pretty, but here's a screenshot(s). 

With Notifee using `createTriggerNotification`
<img width="380" alt="Screenshot 2021-01-11 at 03 51 58" src="https://user-images.githubusercontent.com/14185925/104636875-ed888980-569b-11eb-99da-2316808e333a.png">

Next, using action listeners, after user has clicked play:

<img width="363" alt="Screenshot 2021-01-11 at 03 48 55" src="https://user-images.githubusercontent.com/14185925/104636729-b4e8b000-569b-11eb-9833-e75f3b4b1507.png">

**Comment by VivienTournie** [comment]
I didn't expect such a quick answer :)

Your solution seems promising, and I am well aware that this is a difficult feature, so thank you for your hard work !


> The other thing and I think how we can get it to work initially is to create what looks like a media style notification but without the session token. Then when the user clicks play, you can call TrackPlayer.play() where their notifications will take over, if that makes sense.

I'm a bit concerned about the "user clicking on play button" part. Does it mean the user would need to manually click play button for the sound to be played ? I probably misunderstood your explaination about that part.
To be sure : For me, the sound must be played automatically when the TriggerNotification appears, because it's the purpose of this type of notification. Once the music starts, the "Pause" button becomes available. Can you confirm this use case ?

Being able to manually click the play/pause buttons to listen again should happen only after the automatic start of the sound. What is your opinion ?

**Comment by helenaford** [comment]
No problem, it's something we're keen to add to the library too :)

Interesting use case. I don't think you can do that on iOS (when a sound clip is attached) but if we go with the solution I propose, you can start playing the track when the `DELIVERED` event is fired, if that's what you're describing?

```
Notifee.onForegroundEvent(async event => {
   // To Automatically play once notification is received
    if (event.type === EventType.DELIVERED) {
      await TrackPlayer.add({
        id: 'local-track-1',
        url: localTrack,
        title: 'Pure (Demo) from handler',
        artist: 'David Chavez',
        artwork: 'https://storage.googleapis.com/static.invertase.io/assets/avatars/female.png',
        duration: 28,
      });
  
      await TrackPlayer.play();
     }
      
      // To play once action is press
      if (event.type === EventType.ACTION_PRESS && event.detail?.pressAction?.id === 'play') {
         // play track
      }
  }
```

Here's a preview of the API:

  ```
  Notifee.displayNotification({
      id: 'local-track',
      title: 'Song Title,
      body: 'Artist',
      android: {
        largeIcon: 'url/to/album/artwork',
        style: {
           type:  AndroidStyle.MEDIA,
        },
        actions: [
          {
            title: 'Play',
            pressAction: {
              id: AndroidMediaStyleAction.PLAY, <-- unique to media style notifications
            },
            icon: 'value-of-custom-icon' <--  to overwrite the default play icon
          },
        ],
        channelId: 'channelId',
      },
    })
```

**Comment by VivienTournie** [comment]
> Interesting use case. I don't think you can do that on iOS (when a sound clip is attached) but if we go with the solution I propose, you can start playing the track when the `DELIVERED` event is fired, if that's what you're describing?

Yes this is exactly what I wanted to describe ! Although I love English, sometimes being French doesn't help me express my ideas very clearly 😆
If your solution works the same way on iOS using the `DELIVERED` event, then it's perfect !

**Comment by helenaford** [comment]
I totally get it, and it's always a little tricky to try and describe how things work on a GitHub issue 😆 Hopefully, the p/r I've pushed up helps clarify what my proposed solution is. I've detailed out steps if you wanted to try it out, and see if it works as you expected/meets your needs. The overall API shouldn't change, e.g. using title for song name, body for artist, largeIcon for artwork...

**Comment by helenaford** [comment]
Hi All, we have some questions about the feature enhancement. There is a pending p/r with a way to recreate the notification in the screenshot below.  The API updates (https://github.com/notifee/react-native-notifee/pull/231) include setting the style as 'MEDIA' and having the default icons play, stop e.t.c. so you can easily display a media-style notification. This solution would require a library like react native track player to manage playing the track, and their notifications would take over.

<img width="429" alt="Screenshot 2021-02-15 at 09 49 59" src="https://user-images.githubusercontent.com/14185925/107930679-35d4e900-6f73-11eb-9a19-f8e086285f3a.png">

@VivienTournie @sampsonjoliver @SaeedZhiany, and all who are interested in this feature, please we'd love to get some feedback. 

Does this meet your requirements/use case?

**Comment by sampsonjoliver** [comment]
@helenaford It's awesome to see you pushing this feature forward, thank you :)

I've since moved off of my last project, though have since moved on to one that is ironically _also_ using `react-native-video`. I likely won't have time to try implementing this (though @davrosull may be interested) but happy to provide feedback.

RN Video is a `<Video>` component that takes a `paused` bool and `onProgress` callback as props, and exposes a `seek` method on its ref. It doesn't provide a playback notification of any kind, unlike track-player. I've previously linked it up manually with `react-native-music-control`, however, this particular lib yields many issues on Android.

Taking your provided example, I imagine one possible implementation path to integrate with notifee could look something roughly like the below?

```js
const Player = () => (
  const videoRef = useRef();
  const [isPaused, setPaused] = useState(false)
  useEffect(() => updateMediaNotification(isPaused) , [isPaused]);

  Notifee.onForegroundEvent(async event => {
    if (event.type === EventType.ACTION_PRESS && isPlayOrPauseAction(event)) {
      setPaused( ... )
    }
    if (event.type === EventType.ACTION_PRESS && isSeekAction(event)) {
      ref.seek( ... )
    }
  }

  <RNVideo
    ref={videoRef}
    paused={isPaused}
  />
)

const updateMediaNotification ( isPaused) => Notifee.displayNotification({
  ...
  android: {
     ...,
     actions: [{
        pressAction: { id: isPaused ? AndroidMediaStyleAction.PLAY : AndroidMediaStyleAction.PAUSE },
     }],
  },
})
```

Hopefully this little bit of pseudocode highlights some of the need for all the video player apps out there, and offers a decent starting place to anyone who'd like to give this a go and verify :)

**Comment by helenaford** [comment]
@sampsonjoliver thanks for the feedback! And the use case/example. The question I have is would this video be playing in the background, which is why you would want the user to play and pause the video via a notification or i guess a smart watch? 

We're debating if this feature belongs inside notifee, and if it does, to what extend do we need to integrate with the media player e.t.c . One of the use cases suggested to us was to trigger a notification, which kind of makes sense, which is what the current solution supports; a very lightweight integration - so visually it looks like a media style notification but then another library takes over.

The use case you've suggested, seems like it would require an implementation like react-native-music-controls but inside notifee?

**Comment by sampsonjoliver** [comment]
@helenaford great question. My previous workplace dealt with educational videos, and we found that, for our users, listening to the videos with the app in background while commuting to/from work was a big use case. Multitasking was relatively common. To that end `react-native-video` takes a `playInBackground: boolean` prop.

Most of the issues my team encountered with `react-native-music-controls` were due to its implementation of its underlying Android service, and bugs would occur where the media notification became unresponsive or the service would crash.

Without having implemented it, I'm not sure how notifee would differ in this use case. But it seems like so long as the app is alive (which it needs to be for rnvideo to still be playing in background) then the notification's `onForeground` handlers will still trigger and drive the playback state of the video? In which case, this solution would be fine :)

Of course it would be _nice_ to see tighter integrations, or more of a golden path, for integrating with these specific libs -- like a `notifee.wrapRNVideoWithMediaControls(RNVideo)` hoc, or something deeper where notifee attaches directly to the media stream or exoplayer events, but I can certainly understand how that might be outside your wheelhouse. Especially as there is the iOS half of the puzzle to consider as well. Possibly it's to work with the teams behind those libs on how to build their own first-party media notifications.
